### ISSUE TITLE
Glitch with Chrome + Material Design

### ISSUE THREAD

**Issue by THeK3nger** [KeenRivals/chrome-developer-edition-dark#1]
Hi! 

I'm testing this amazing theme on the new Material look of Chrome and I noticed that the blue tab color ends just some pixels earlier than it should. Look at the picture.

![theme](https://cloud.githubusercontent.com/assets/133159/15923926/d79a238e-2e2f-11e6-9172-2a3fb452eb47.png)

I know material design is still not "stable", but keep an eye on this for when material design will be the default! :)

**Comment by KeenRivals** [comment]
I'm aware of this issue. I can't wait for material to come out! I [have a material design branch](https://github.com/KeenRivals/chrome-developer-edition-dark/tree/material) ready for when it's released. Thus far I have leaned towards not putting this material version on the Play Store because I don't want to have two identical themes once material lands in Chrome proper.

**Comment by THeK3nger** [comment]
Ok! I'll wait for the official release, then! :)

**Comment by dhaynespls** [comment]
Hey @KeenRivals as of Chrome 55 it looks like Material is the default theme. If you want to hold off merging then I'd suggest at the very least linking that material design branch in your README so that it is easier to find. Thanks for the fix!

**Comment by KeenRivals** [comment]
Material has been default for a few weeks now iirc. I've been waiting it out, but I think it's time. I've just pushed the new version to the web store.

**Comment by dhaynespls** [comment]
Awesome, thanks!
