### ISSUE TITLE
theme formating in chrome window broken

### ISSUE THREAD

**Issue by masoxs** [KeenRivals/chrome-developer-edition-dark#9]
instead of being selected and blue only in the selected tab, now it is broken and in the below tabs selectors/ address bar

![Screenshot of a chrome new window showing the issue with the theme formatting.](https://github.com/KeenRivals/chrome-developer-edition-dark/assets/43620218/5afc31b7-b035-4569-921c-3b52e0ad914c)

Chrome Version 116.0.5845.180 (Official Build) (64-bit)
Win 10

**Comment by KeenRivals** [comment]
I've been experimenting with this and I can't fix this and keep the strong blue highlight. Chrome now repeats the image used for the theme_toolbar at the top of the active tab and at the top of the omnibox area. This causes the blue highlight to start at the top of the tab and restart at the top of the main toolbar area.

 You can see this in other themes that used to rely on this _not_ being the behavior such as this [Rick and Morty Theme](https://chrome.google.com/webstore/detail/rick-and-morty-theme/mjlbjnagciolegpimabclliiolgeobdn?hl=en), [Sahara](https://chrome.google.com/webstore/detail/sahara/gnplnldbhjbakploidcdefoebhmengpm?hl=en), and [Pink Triangles](https://chrome.google.com/webstore/detail/pink-triangles/fklljnhmbagigkninckdfeknliepoock?hl=en). My theme is probably the worst affected by this change due to relying on that fame/toolbar alignment.

This new behavior could probably be considered a bug in Chrome's theme engine but I'm not willing to spend any amount of time trying to convince them to fix it. I will push an update to remove the blue highlight instead.
